name: woc_events_mobile
description: WOC Registration App.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: '>=0.11.3+12'
  logging: ^0.11.3+2
  path_provider: ^0.4.1
  uuid: ^1.0.3
  intl: ^0.15.7
  font_awesome_flutter: ^8.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  url_launcher: ^4.0.2
  google_maps_flutter: ^0.0.3+3
  queries: ^0.1.4
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/LauncherIcon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - secrets.json

  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/avenir-next-bold.ttf
          weight: 700
        - asset: fonts/avenir-next-italic.ttf
          style: italic
        - asset: fonts/avenir-next-regular.ttf
        - asset: fonts/avenir-next-thin.ttf
          weight: 300